#! /bin/bash

# Program: x-html
# Usage: x-html filename.html

FILENAME="$1"
X_SIZE=1024

DATE="$(date)"
CONTENT_SIZE=$(stat -f "%z" $FILENAME)

if [[ ${CONTENT_SIZE} -lt ${X_SIZE} ]] ; then
   HTML_TYPE="text/html" 
else
   HTML_TYPE="application/x-html" 
fi 


echo HTTP/1.1 200 Okay
echo Server: premortal/cit-384/${USER} 
echo Date: ${DATE}
echo Content-type: ${HTML_TYPE}
echo Content-length: ${CONTENT_SIZE}
echo ""

if (( CONTENT_SIZE < X_SIZE )) ; then
  cat ${FILENAME}
else
  cat ${FILENAME} | compress - | base64
fi 
